"""
Supports two modes:

  1. OFFLINE  (default for training w/ generated data)
     Loads from .npy files produced by generate_training_data.py.
     No Convex connection needed.

  2. ONLINE  (production)
     Pulls live data from Convex.

Usage (offline):
    train_loader, test_loader = get_data_loader(mode="offline", data_dir="training/")

Usage (online / original behaviour):
    train_loader, test_loader = get_data_loader(mode="online")
"""

from pathlib import Path

import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader, random_split


# ── Dataset

class EventRecDataset(Dataset):
    """
    Each sample is a BPR triplet: (user_weight_vec, pos_event_multihot, neg_event_multihot).

    Args:
        user_weights:  Tensor of shape (num_users, num_tags)
        event_tags:    Tensor of shape (num_events, num_tags)
        triplets:      LongTensor of shape (N, 3)  [user_idx, pos_idx, neg_idx]
                       If None, triplets are sampled randomly at __getitem__ time.
    """

    def __init__(
        self,
        user_weights: torch.Tensor,
        event_tags: torch.Tensor,
        triplets: torch.Tensor | None = None,
    ):
        self.user_weights = user_weights          # (num_users, num_tags)
        self.event_tags = event_tags              # (num_events, num_tags)
        self.triplets = triplets                  # (N, 3) or None

    def __len__(self) -> int:
        if self.triplets is not None:
            return len(self.triplets)
        return len(self.user_weights)

    def __getitem__(self, idx: int):
        if self.triplets is not None:
            u_idx, pos_idx, neg_idx = self.triplets[idx]
            user = self.user_weights[u_idx]
            pos  = self.event_tags[pos_idx]
            neg  = self.event_tags[neg_idx]
        else:
            # random sampling (Not preffered)
            user = self.user_weights[idx]
            pos_idx = torch.randint(len(self.event_tags), (1,)).item()
            neg_idx = torch.randint(len(self.event_tags), (1,)).item()
            pos = self.event_tags[pos_idx]
            neg = self.event_tags[neg_idx]

        return user, pos, neg


# ── Loaders ────────────────────────────────────────────────────────────────────

def _make_loaders(dataset: EventRecDataset, batch_size: int = 32):
    train_size = int(0.8 * len(dataset))
    test_size  = len(dataset) - train_size
    train_set, test_set = random_split(dataset, [train_size, test_size])
    train_loader = DataLoader(train_set, batch_size=batch_size, shuffle=True)
    test_loader  = DataLoader(test_set,  batch_size=batch_size, shuffle=False)
    return train_loader, test_loader


def _load_offline(data_dir: str, batch_size: int = 32):
    """Load from .npy files generated by generate_training_data.py."""
    d = Path(data_dir)
    user_weights = torch.from_numpy(np.load(d / "user_tag_weights.npy"))
    event_tags   = torch.from_numpy(np.load(d / "event_tag_multihot.npy"))
    triplets     = torch.from_numpy(np.load(d / "triplets.npy")).long()

    dataset = EventRecDataset(user_weights, event_tags, triplets=triplets)
    return _make_loaders(dataset, batch_size)


def _load_online(batch_size: int = 32):
    """Pull live data from Convex"""
    # Imports only needed here
    from utils.utils import get_client

    client = get_client()

    # Pull and shuffle users
    users = client.query("data_ml/universal:queryAll", {"table_name": "users"})
    user_ids = [u["_id"] for u in users]
    np.random.shuffle(user_ids)

    all_weights = client.query("data_ml/updateUserPreferences:getAllUserTagWeights", {})
    weight_map  = {row["userId"]: row["weights"] for row in all_weights}
    user_weights_dict = {uid: weight_map[uid] for uid in user_ids if uid in weight_map}

    user_weights = torch.tensor(
        list(user_weights_dict.values()), dtype=torch.float32
    )

    # Pull event tags
    event_tags_raw = client.query("data_ml/universal:queryAll", {"table_name": "eventTags"})
    num_tags = max(row["tagIdx"] for row in event_tags_raw) + 1
    event_tags = torch.zeros((len(event_tags_raw), num_tags), dtype=torch.float32)

    dataset = EventRecDataset(user_weights, event_tags, triplets=None)
    return _make_loaders(dataset, batch_size)


def get_data_loader(
    mode: str = "offline",
    data_dir: str = "training/training_data/",
    batch_size: int = 32,
):
    """
    Args:
        mode:      "offline" (load from .npy files) | "online" (pull from Convex)
        data_dir:  path to directory containing .npy files (offline mode only)
        batch_size: DataLoader batch size

    Returns:
        (train_loader, test_loader)
    """
    if mode == "offline":
        return _load_offline(data_dir, batch_size)
    elif mode == "online":
        return _load_online(batch_size)
    else:
        raise ValueError(f"Unknown mode '{mode}'. Use 'offline' or 'online'.")
